### ISSUE TITLE
Failed to activate the go-quick-import package when starting Atom 1.19.0

### ISSUE THREAD

**Issue by Vrakfall** [mastercactapus/atom-go-quick-import#5]
[Enter steps to reproduce:]

1. Just start Atom v`1.19.0` with the package already installed

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: "Manjaro Linux"
**Thrown From**: [go-quick-import](https://github.com/mastercactapus/atom-go-quick-import) package 0.3.1

### Stack Trace

Failed to activate the go-quick-import package

```
At interface conversion: interface is map[string]interface {}, not func(...interface {}) *js.Object

Error: interface conversion: interface is map[string]interface {}, not func(...interface {}) *js.Object
    at /packages/go-quick-import/lib/modimport.js:1407:17)
    at /packages/go-quick-import/lib/modimport.js:1446:3)
    at /packages/go-quick-import/lib/modimport.js:1335:5)
    at /packages/go-quick-import/lib/modimport.js:15474:16)
    at /packages/go-quick-import/lib/modimport.js:17911:16)
    at /packages/go-quick-import/lib/modimport.js:23630:12)
    at /packages/go-quick-import/lib/modimport.js:31960:12)
    at /packages/go-quick-import/lib/modimport.js:1466:19)
    at /packages/go-quick-import/lib/modimport.js:1523:5)
    at /packages/go-quick-import/lib/modimport.js:1499:3)
    at /packages/go-quick-import/lib/modimport.js:31978:1)
    at /packages/go-quick-import/lib/modimport.js:31981:4)
    at /packages/go-quick-import/lib/modimport.js:31984:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/go-quick-import/lib/go-quick-import-view.js:19:18)
    at /packages/go-quick-import/lib/go-quick-import-view.js:213:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/go-quick-import/lib/go-quick-import.js:7:26)
    at /packages/go-quick-import/lib/go-quick-import.js:57:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:887:35)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:242:22)
    at /usr/share/atom/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at /usr/share/atom/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:645:40)
    at /usr/share/atom/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:603:52)
    at /usr/share/atom/resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.2.0 
advanced-open-file 0.16.6 
ambiance-dark-syntax 0.1.1 
ambiance-dark-ui 0.51.1 
ambiance-pro-ui 0.4.1 
atom-beautify 0.30.5 
atom-ember-author-kit 0.8.3 
atom-slice 0.0.5 
atom-ternjs 0.18.3 
atom-typescript 11.0.6 
atom-yeoman 0.3.15 
autocomplete-java 1.2.7 
autocomplete-json 5.5.0 
autocomplete-modules 1.6.10 
browser-plus 0.0.98 
busy-signal 1.4.3 
color-picker 2.2.5 
convert-to-utf8 0.2.4 
cpp-refactor 2.2.3 
docblockr 0.11.0 
editor-stats 0.17.0 
ember-cli-helper 0.9.0 
ember-snippets 2.1.0 
ember-tabs 2.4.3 
emoji-syntax 1.7.2 
fancy-bracket-matcher 1.0.1 
file-watcher 1.1.0 
filecolor 0.4.0 
git-history 3.3.0 
git-plus 7.9.3 
git-time-machine 1.5.9 
gitignore-snippets 0.2.5 
go-debug 1.5.0 
go-oracle 0.2.1 
go-plus 5.5.5 
go-quick-import 0.3.1 
go-signature-statusbar 1.2.1 
go-types 1.2.1 
hyperclick 0.1.3 
intentions 1.1.5 
js-hyperclick 1.11.0 
js-refactor 0.7.5 
json-schema 0.1.15 
json-to-go-struct 0.0.5 
jumpy 3.1.3 
language-cisco 1.4.0 
language-docker 1.1.8 
language-gitignore 0.3.0 
language-pug 0.0.21 
linter 2.2.0 
linter-docker 0.2.0 
linter-eslint 8.2.1 
linter-javac 1.9.4 
linter-js-yaml 1.2.7 
linter-markdown 5.1.0 
linter-pug 1.3.1 
linter-ui-default 1.6.4 
markdown-pdf 1.5.4 
markdown-scroll-sync 2.1.2 
merge-conflicts 1.4.5 
meteor-helper 0.29.0 
meteorjs-snippets-es6 1.3.0 
minimap 4.29.6 
minimap-find-and-replace 4.5.2 
minimap-split-diff 0.3.7 
node-debugger 1.10.1 
omnisharp-atom 0.31.2 
package-list 0.1.2 
pigments 0.40.2 
refactor 0.11.5 
run-in-atom 1.0.5 
set-syntax 0.3.2 
seti-syntax 1.1.3 
seti-ui 1.9.0 
split-diff 1.4.3 
ssh-config 0.10.1 
tab-toggler 0.1.1 
terminal-plus 0.14.5 
tidy-markdown 3.0.1 
todo-show 1.11.0 
toggle-quotes 1.0.1 
tree-ignore 0.6.2 
yaml-path-copy 2.1.6 
```

**Comment by Nicolab** [comment]
Hello,

Same here #6 but the stack trace is different (caused by double babel-polyfill instance).
