### ISSUE TITLE
Failed to activate the go-quick-import package when starting Atom 1.28.1

### ISSUE THREAD

**Issue by Nicolab** [mastercactapus/atom-go-quick-import#6]
Hello,

This error is displayed when I start Atom.

[Enter steps to reproduce:]

1. Just start Atom 1.28.1 with the package already installed (last month, it worked)

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Ubuntu 16.04.4
**Thrown From**: [go-quick-import](https://github.com/mastercactapus/atom-go-quick-import) package 0.3.1

### Stack Trace

Failed to activate the go-quick-import package

```
At only one instance of babel-polyfill is allowed

Error: only one instance of babel-polyfill is allowed
    at /packages/go-quick-import/node_modules/babel-polyfill/lib/index.js:10:9)
    at /packages/go-quick-import/node_modules/babel-polyfill/lib/index.js:29:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/go-quick-import/lib/go-quick-import-view.js:11:1)
    at /packages/go-quick-import/lib/go-quick-import-view.js:213:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/go-quick-import/lib/go-quick-import.js:7:26)
    at /packages/go-quick-import/lib/go-quick-import.js:57:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:782:33)
    at Package.activateNow (/usr/share/atom/resources/app/src/package.js:220:40)
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
api-docs 0.0.6 
atom-alignment 0.13.0 
atom-beautify 0.32.5 
atom-commander 0.11.0 
atom-ide-ui 0.12.0 
atom-mermaid 3.3.1 
atom-updater-linux 1.2.2 
autocomplete-paths 2.12.2 
autocomplete-python 1.10.5 
bug-report 0.7.1 
busy-signal 1.4.3 
color-picker 2.3.0 
command-logger 0.23.0 
dark-ambiance-syntax 0.0.0 
diagrams 0.28.4 
docblockr 0.13.7 
docker 0.8.0 
document-outline 2.1.2 
enhanced-tabs 1.7.0 
expose 0.15.0 
file-icons 2.1.22 
file-types 0.5.5 
foldername-tabs 0.2.4 
git-change-marker 0.16.0 
git-control 0.9.0 
git-history 3.3.0 
git-log 0.4.1 
git-plus 7.12.0 
git-time-machine 2.1.0 
go-debug 1.6.2 
go-plus 5.8.3 
go-quick-import 0.3.1 
go-signature-statusbar 1.2.3 
go-types 1.2.1 
highlight-column 0.5.4 
highlight-line 0.12.0 
highlight-selected 0.14.0 
hyperclick 0.0.0 
hyperclick-markdown 0.2.2 
ide-css 0.3.0 
ide-docker 0.0.2 
ide-go 0.7.0 
ide-html 0.4.2 
ide-typescript 0.7.6 
ide-yaml 0.4.3 
intentions 1.1.5 
js-hyperclick 1.13.0 
json-to-go-struct 0.0.5 
language-docker 1.1.8 
language-ejs 0.4.0 
linter 2.2.0 
linter-csslint 2.0.1 
linter-docker 0.3.2 
linter-eslint 8.4.1 
linter-flake8 2.3.0 
linter-jshint 3.1.8 
linter-jsxhint 0.1.2 
linter-php 1.5.1 
linter-phpmd 2.0.0 
linter-ui-default 1.7.1 
local-history 4.3.1 
MaPerWiki 0.1.27 
markdown-preview-enhanced 0.15.6 
markdown-themeable-pdf 1.2.1 
markdown-writer 2.7.4 
merge-conflicts 1.4.5 
minimap 4.29.8 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-pigments 0.2.2 
minimap-split-diff 0.3.7 
monokai 0.24.0 
open-files 0.8.2 
open-git-modified-files 0.2.4 
pdf-view 0.70.0 
pigments 0.40.2 
project-colorize 0.3.0 
react 0.18.0 
regex-railroad-diagram 0.19.4 
set-syntax 0.4.0 
show-origin 0.2.0 
sort-lines 0.18.0 
split-diff 1.5.2 
string-looper 0.1.2 
tab-numbers 0.6.1 
tabs-closer 0.16.0 
tabularize 0.2.5 
teletype 0.13.3 
terminal-plus 0.14.5 
todo-show 2.3.0 
tool-bar 1.1.7 
tool-bar-markdown-writer 0.3.1 
turbo-javascript 1.4.0 
unitjs 1.0.0 
```

**Comment by yedidmh** [comment]
Any updates? Same here, can't figure out how to resolve.

**Comment by Nicolab** [comment]
Hello,

I have resolved by removing this package (go-quick-import). With https://atom.io/packages/go-plus the imports (and other features) work perfectly.

**Comment by Vrakfall** [comment]
Looks more like a workaround. :P
